### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by scarzxx** [350d/70Mai_A800S_Firmware#1]
What program did you used to edit the 70mai a800s firmware? Thank you

**Comment by 350d** [comment]
Here is a good start point https://github.com/boba-nopasaran-dr2800/Kitchen

**Comment by scarzxx** [comment]
> Here is a good start point https://github.com/boba-nopasaran-dr2800/Kitchen

isn't that for linux ?

**Comment by 350d** [comment]
Yes. Ununtu will work just fine.

**Comment by scarzxx** [comment]
nah im not able to figure it out :D getting a lot of errors . rootfs and others
