### ISSUE TITLE
Low sound level on font_car_start.wav

### ISSUE THREAD

**Issue by p-genov** [350d/70Mai_A800S_Firmware#10]
I really like the firmware with all disctrete tones, but I cant hear the tone for the "70mai_font_car_start.wav" even when there is quiet in the car. On High Speaker level, I can hear a faint Poping sound, when the camera detects the vehicle ahead moving. For test I have enabled the other two options in ADAS, for Lane departure and Collision warning. They are strong enough even on Low speaker level.
Can you replace the sound of "70mai_font_car_start.wav" with "70mai_lane_departure.wav" or something similar?

**Comment by juuura** [comment]
I join, a very quiet sound of the beginning of movement. Help with this problem.

**Comment by 350d** [comment]
Updated 70mai_font_car_start.wav to 70mai_lane_departure.wav
