### ISSUE TITLE
50MBIT FW Failed on Update

### ISSUE THREAD

**Issue by akenov** [350d/70Mai_A800S_Firmware#13]
Hello,

I have unzipped the 50MBIT firmware file and copied the .bin file to the main folder of the SD card, added a .jpg logo according to the README plus the log and setup scripts. When I reboot, it goes into firmware update mode and eventually it says "Updated failed. Rebooting..." and nothing changed. I have double checked the .bin file is properly unzipped and byte-wise copied over the SD card. The scripts and the logo never came into play. I assume your new FW makes use of them but since it never installed it never came to execute them.

I have already have the latest 1.0.19ww OTA firmware installed on the device from the official app. Perhaps this is why it doe not want to install a new one?

Any feedback is much appreciated

**Comment by 350d** [comment]
You need to flash older firmware first to update to .19 version again. You cant update 19 to 19 unfortunately.
