### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by nnciprian** [350d/70Mai_A800S_Firmware#14]
Hello, i'm running latest official firmware. It seems I can't upgrade to modded one;

Is it because of the custom firmware version number?
Ty

![20230723_182219](https://github.com/350d/70Mai_A800S_Firmware/assets/12816820/c65017c9-6b39-4eaa-b85d-e8b09b81e536)

**Comment by dennisb1** [comment]
Downgrade first and then upgrade to the custom. 

Manual should be more clear about this I agree.

**Comment by 350d** [comment]
Use txt file from firmware folder to force update to same version or downgrade to older one and upgrade again.

**Comment by nnciprian** [comment]
I put both files (.bin and the FORCEUPDATE.txt ) when i get this error

**Comment by 350d** [comment]
Downgrade first then

**Comment by nnciprian** [comment]
Thanks,  is there a guide and .bin somewhere?

**Comment by dennisb1** [comment]
https://github.com/350d/70Mai_A800S_Firmware/blob/main/Firmware/FW_DR2800_OTA.zip

**Comment by nnciprian** [comment]
so you mean flash the OTA first then the modded one?

**Comment by 350d** [comment]
any ota older than current one will work for sure i guess

**Comment by nnciprian** [comment]
the OTA one here is the same I have installed right now (1.0.19ww)
Can you please upload an older one also?

**Comment by nnciprian** [comment]
also does the modded one enable ssh/telnet access? maybe we can try doing some more fiddling there. I would try to change the function of some of the buttons, i would like to be able to shoot a picture instead of switching to back camera

**Comment by 350d** [comment]
19 ota should work for downgrade, it has older build time. ftp and telnet up and running in this custom fw by default. Admin for telnet login and empty password should work. Empty login/pass for ftp.

**Comment by 350d** [comment]
14 ota https://drive.google.com/drive/mobile/folders/1p1KjXXAbCd-NoTnMkuhY2NT06lbckPph?usp=share_link

**Comment by nnciprian** [comment]
Confirm, it works by downgrading to 14 then updating to modded 19;
Thanks for quick replies guys. I will try to contribute to this as well

**Comment by nnciprian** [comment]
> Confirm, it works by downgrading to 14 then updating to modded 19; Thanks for quick replies guys. I will try to contribute to this as well



> 19 ota should work for downgrade, it has older build time. ftp and telnet up and running in this custom fw by default. Admin for telnet login and empty password should work. Empty login/pass for ftp.

root with no pass worked :)
Thx!
