### ISSUE TITLE
Bricked after logo update

### ISSUE THREAD

**Issue by ngsmg** [350d/70Mai_A800S_Firmware#2]
After loading a new logo.jpg the cam stuck in bootloop with a greenish broken screen content. Since than I cannot run any other autorun script as a means to fix the issue, so practically the cam is bricked. Please help me find a solution, also please place a warning on logo update saying this can happen (unless it can be easily fixed, in which I have not yet succeeded)

**Comment by ngsmg** [comment]
Managed to unbrick via FW update. Put nothing but the FW bin on the SD card, and turned the cam on while charger already plugged in. Got original FW files from 70mai support.

**Comment by 350d** [comment]
Hello! This device are hard to be bricked. You can recover it with sd card and firmware bin file on it. So, you can flash clean firmware from this repo to unbrick it too. Just put sd card and powercycle device.In your specific case - you need standard jpg without any optimizations. Check example screenshot for specific photoshop settings to save it.

**Comment by elkarto** [comment]
> Managed to unbrick via FW update. Put nothing but the FW bin on the SD card, and turned the cam on while charger already plugged in. Got original FW files from 70mai support.

Hello

Could you share the files with the original firmware?


Is there any other way to go back to the original firmware?

Thanks in advance

**Comment by 350d** [comment]
[OTA Firmware](https://github.com/350d/70Mai_A800S_Firmware/blob/main/Firmware/FW_DR2800_OTA.zip)

**Comment by elkarto** [comment]
Wow, that's really fast, thank you very much.

I'm definitely going to try your firmware, great job. I hope that improvements can be added step by step.

**Comment by elkarto** [comment]
Logo successfully changed. 

It's not a big change because the camera is always powered and never turns off, but... Because we can.


I have attached it just in case someone might find it useful.

![logo_bmw_f11](https://user-images.githubusercontent.com/36958524/214526168-014881dd-7e80-447d-aa01-230154f51ade.jpg)

Just rename it to logo.jpg in order to use the script.
