### ISSUE TITLE
RTSP Stream?

### ISSUE THREAD

**Issue by tibudiyanto** [350d/70Mai_A800S_Firmware#3]
Hi, I was wondering is there a build in rtsp stream on this firmware (or in the original firmware)? 

Thanks

**Comment by 350d** [comment]
Front/back camera streams:

rtsp://dashcamip/liveRTSP/av4
rtsp://dashcamip/liveRTSP/av5

Just for information - both streams are downscaled to 720p with extremely low bitrate. I've tried to tweak it without any success.

**Comment by tibudiyanto** [comment]
Thanks!

**Comment by elkarto** [comment]
I had also noticed that the rtsp stream had very poor quality in the original firmware.

I'm glad to see that someone has researched about it.


Have you been able to make any progress on it?


Thanks!!!

**Comment by 350d** [comment]
Few options available via `cardv_fifo` interface for bitrate and size but they are don't work for some reason. Binary patching should be involved I guess.
