### ISSUE TITLE
The factory reset menu is initialized and setting is not possible

### ISSUE THREAD

**Issue by sthoonus** [350d/70Mai_A800S_Firmware#6]
After executing the factory reset in the menu, WIFI tethering is not possible so that 70 mai setting is not possible at all.
(WIFI name does not appear, I can connect the device via wifi tethering.)

How can I recover in this case?

**Comment by 350d** [comment]
Hello! Latest firmware was tested against factory reset and connect/reconnect with 70Mai app. Make sure you have used fixed wifi network name and fixed password to connect to device wifi.

**Comment by 350d** [comment]
You can recover any time by flashing OTA firmware via sd card. Power of the device. Insert SD card with firmware file on it. Power up the device.

**Comment by sthoonus** [comment]
Sorry for checking late.
It's working well again after recovering as you said.
Thank you very much.
