### ISSUE TITLE
Unable to update logo

### ISSUE THREAD

**Issue by ankurpandeyvns** [350d/70Mai_A800S_Firmware#8]
The camera just keeps on restarting when I place the autorun_logo script and the logo.

**Comment by 350d** [comment]
Check debug log file on SD card about your startup script errors or something.

**Comment by ankurpandeyvns** [comment]
No errors on the log file. It stays blank. It stops restarting only when I remove the logo.
Also, I'm using the logo in this repo for testing. It worked on previous firmware but not on this.

**Comment by 350d** [comment]
Make sure your card are not read only. In startup script there is a `mv` command to move script itself to complete folder to avoid boot loop.

**Comment by 350d** [comment]
Sorry, I can't confirm your issue. I've tried to flash latest firmware from Firmware folder. After flash I've copied logo script and test logo JPG from Assets folder and rebooted the device again. Logo replaced and no any boot loop situation. Please check your system.
